language: c

dist: focal

os: linux

addons:
  apt:
  - python2
  - python3
  - cargo
  - peg

env:
  global:
  - DOCKER_REGISTRY=ghcr.io
  - DOCKER_REPOSITORY=arm64-compat/redis-stack

stages:
- build

git:
  submodules: false

services:
- docker

jobs:
  include:
  - &redis-bloom
    name: "Build Redis Bloom"
    stage: build
    arch: arm64
    before_script:
    - cd RedisBloom
    - git submodule update --init --recursive
    - make setup
    script:
    - make
    workspaces:
      create:
        name: redis-bloom-${TRAVIS_CPU_ARCH}
        paths:
        - redisbloom.so
  - &redis-json
    name: "Build Redis JSON"
    stage: build
    arch: arm64
    before_script:
    - cd RedisJSON
    - git submodule update --init --recursive
    - make setup
    script:
    - make
    workspaces:
      create:
        name: redis-json-${TRAVIS_CPU_ARCH}
        paths:
        - bin/linux-arm64v8-release/rejson.so*
  - &redis-search
    name: "Build Redis Search"
    stage: build
    arch: arm64
    before_script:
    - cd RediSearch
    - git submodule update --init --recursive
    - make setup
    script:
    - make
    workspaces:
      create:
        name: redis-search-${TRAVIS_CPU_ARCH}
        paths:
        - bin/linux-arm64v8-release/search/redisearch.so*
  - &redis-graph
    name: "Build Redis Graph"
    stage: build
    arch: arm64
    before_script:
    - cd RedisGraph
    - git submodule update --init --recursive
    script:
    - make
    workspaces:
      create:
        name: redis-graph-${TRAVIS_CPU_ARCH}
        paths:
        - src/redisgraph.so*
  - &redis-timeseries
    name: "Build Redis Timeseries"
    stage: build
    arch: arm64
    before_script:
    - cd RedisTimeSeries
    - git submodule update --init --recursive
    - make setup
    script:
    - make
    workspaces:
      create:
        name: redis-timeseries-${TRAVIS_CPU_ARCH}
        paths:
        - bin/redistimeseries.so*
  - <<: *redis-bloom
    arch: amd64
  - <<: *redis-json
    arch: amd64
  - <<: *redis-search
    arch: amd64
  - <<: *redis-graph
    arch: amd64
  - <<: *redis-timeseries
    arch: amd64
  - &build-image
    name: "Build Image"
    stage: docker-build
    arch: arm64
    workspaces:
      use:
      - redis-bloom-${TRAVIS_CPU_ARCH}
      - redis-graph-${TRAVIS_CPU_ARCH}
      - redis-json-${TRAVIS_CPU_ARCH}
      - redis-search-${TRAVIS_CPU_ARCH}
      - redis-timeseries-${TRAVIS_CPU_ARCH}
    git:
      clone: false
    script: ls
  - <<: *build-image
    arch: amd64
