language: c

dist: focal

os: linux

addons:
  apt:
  - python2
  - python3
  - cargo
  - peg

env:
  global:
  - DOCKER_REGISTRY=ghcr.io
  - DOCKER_REPOSITORY=arm64-compat/redis-stack

stages:
- build

git:
  submodules: false

services:
- docker

jobs:
  include:
  - name: "Build Redis Bloom"
    stage: build
    arch: arm64
    before_script:
    - cd RedisBloom
    - git submodule update --init --recursive
    - make setup
    script:
    - make
    workspaces:
      create:
        name: redis-bloom
        paths:
        - redisbloom.so
  - name: "Build Redis JSON"
    stage: build
    arch: arm64
    before_script:
    - cd RedisJSON
    - git submodule update --init --recursive
    - make setup
    script:
    - make
    workspaces:
      create:
        name: redis-json
        paths:
        - bin/linux-arm64v8-release/rejson.so*
  - name: "Build Redis Search"
    stage: build
    arch: arm64
    before_script:
    - cd RediSearch
    - git submodule update --init --recursive
    - make setup
    script:
    - make
    workspaces:
      create:
        name: redis-search
        paths:
        - bin/linux-arm64v8-release/search/redisearch.so*
  - name: "Build Redis Graph"
    stage: build
    arch: arm64
    before_script:
    - cd RedisGraph
    - git submodule update --init --recursive
    script:
    - make
    workspaces:
      create:
        name: redis-graph
        paths:
        - src/redisgraph.so*
  - name: "Build Redis Timeseries"
    stage: build
    arch: arm64
    before_script:
    - cd RedisTimeSeries
    - git submodule update --init --recursive
    - make setup
    script:
    - make
    workspaces:
      create:
        name: redis-timeseries
        paths:
        - bin/redistimeseries.so*
  - name: "Build Image"
    stage: docker-build
    arch: arm64
    workspaces:
      use:
      - redis-bloom
      - redis-graph
      - redis-json
      - redis-search
      - redis-timeseries
    git:
      clone: false
    script: ls
