language: c

dist: focal

os: linux

addons:
  apt:
  - python2
  - python3
  - cargo

env:
  global:
  - DOCKER_REGISTRY=ghcr.io
  - DOCKER_REPOSITORY=arm64-compat/redis-stack

stages:
- build

git:
  submodules: false

services:
- docker

jobs:
  include:
  - name: "Build Redis Bloom"
    stage: build
    arch: arm64
    before_script:
    - cd RedisBloom
    - git submodule update --init --recursive
    - make setup
    script:
    - make
  - name: "Build Redis JSON"
    stage: build
    arch: arm64
    before_script:
    - cd RedisJSON
    - git submodule update --init --recursive
    - make setup
    script:
    - make
  - name: "Build Redis Search"
    stage: build
    arch: arm64
    before_script:
    - cd RediSearch
    - git submodule update --init --recursive
    - make setup
    script:
    - make
  # - name: "Build RedisJSON"
  #   stage: build
  #   arch: arm64
  #   before_script:
  #   - make -C RedisJSON setup
  #   script:
  #   - make -C RedisJSON
  # - name: "Build RedisTimeSeries"
  #   stage: build
  #   arch: arm64
  #   before_script:
  #   - make -C RedisTimeSeries setup
  #   script:
  #   - make -C RedisTimeSeries
  # - name: "Build RedisGraph"
  #   stage: build
  #   arch: arm64
  #   before_script:
  #   - make -C RedisGraph setup
  #   script:
  #   - make -C RedisGraph
