language: c

dist: focal

os: linux

env:
  global:
  - DOCKER_REGISTRY=ghcr.io
  - DOCKER_REPOSITORY=arm64-compat/redis-stack

stages:
- build

services:
- docker

jobs:
  include:
  - &redis-bloom
    name: "Build Redis Bloom"
    stage: build
    arch: arm64
    script:
    - docker build -t ghcr.io/arm64-compat/${TRAVIS_CPU_ARCH}/redis/rebloom -f Dockerfile.redisbloom .
  - &redis-json
    name: "Build Redis JSON"
    stage: build
    arch: arm64
    script:
    - docker build -t ghcr.io/arm64-compat/${TRAVIS_CPU_ARCH}/redis/rejson -f Dockerfile.redisjson .
  - &redis-search
    name: "Build Redis Search"
    stage: build
    arch: arm64
    script:
    - docker build -t ghcr.io/arm64-compat/${TRAVIS_CPU_ARCH}/redis/research -f Dockerfile.redisearch .
  - &redis-graph
    name: "Build Redis Graph"
    stage: build
    arch: arm64
    script:
    - docker build -t ghcr.io/arm64-compat/${TRAVIS_CPU_ARCH}/redis/regraph -f Dockerfile.redisgraph .
  - &redis-timeseries
    name: "Build Redis Timeseries"
    stage: build
    arch: arm64
    script:
    - docker build -t ghcr.io/arm64-compat/${TRAVIS_CPU_ARCH}/redis/retimeseries -f Dockerfile.redistimeseries .
  - <<: *redis-bloom
    arch: amd64
  - <<: *redis-json
    arch: amd64
  - <<: *redis-search
    arch: amd64
  - <<: *redis-graph
    arch: amd64
  - <<: *redis-timeseries
    arch: amd64
